# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/home" # the subpath of your site, e.g. /blog/
url: "https://meleepotatostudios.github.io/" # the base hostname & protocol for your site

twitter_username:sirrefhd
github_username: SirrefStrongbow

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman